name: Branch Naming Convention Check
run-name: Branch Name Check for ${{ github.head_ref }}

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          branch_name="${{ github.head_ref }}"
          echo "Checking branch name: $branch_name"

          # Allow system/promoter branches to bypass naming checks
          case "$branch_name" in
            staging|staging-promoter|production-promoter)
              echo "System branch '$branch_name' – skipping naming check"
              exit 0
              ;;
          esac

          if [[ $branch_name =~ ^(feature|bugfix|hotfix)/[a-z0-9_\-]+$ ]]; then
            echo "Branch name follows the naming convention: <type>/<branch-name>"
            echo "Branch name is valid: $branch_name"
          else
            echo "Branch name does not follow the naming convention!"
            echo ""
            echo "BRANCH NAMING REQUIREMENTS:"
            echo "  • Must start with 'feature/', 'bugfix/', or 'hotfix/'"
            echo "  • Must contain only lowercase letters, numbers, underscores, and hyphens"
            echo "  • Examples:"
            echo "    - feature/user_authentication"
            echo "    - bugfix/performance_optimization"
            echo "    - hotfix/critical_fix"
            echo ""
            echo "TO FIX YOUR BRANCH NAME:"
            echo "  1. Rename your current branch:"
            echo "     git branch -m $branch_name feature/your_feature_name"
            echo ""
            echo "  2. Delete the old remote branch:"
            echo "     git push origin --delete $branch_name"
            echo ""
            echo "  3. Push the renamed branch:"
            echo "     git push origin feature/your_feature_name"
            echo ""
            echo "  4. Update your local branch to track the new remote:"
            echo "     git branch --set-upstream-to=origin/feature/your_feature_name"
            echo ""
            echo "Replace 'your_feature_name' with a descriptive name for your feature"
            exit 1
          fi
